import { db } from "./db";
import { products } from "@shared/schema";
import { sql } from "drizzle-orm";

export const sampleProducts = [
  // ═══════════════════════════════════════════
  // JANITORIAL & CLEANING (~10 products)
  // ═══════════════════════════════════════════
  {
    id: "prod-01",
    name: "Heavy-Duty Floor Cleaner Concentrate",
    description: "Industrial-strength alkaline floor cleaner for VCT, ceramic, and concrete surfaces. Dilutes 1:64 for daily cleaning.",
    unitOfMeasure: "Gallon",
    unitPrice: "18.50",
    supplier: "Grainger",
    contract: "OMNIA R-GR-JC-20001",
    availability: "In Stock",
    isEco: false,
    category: "Janitorial & Cleaning",
    specifications: { dilutionRatio: "1:64", ph: "12.5", color: "Blue", scent: "Fresh Pine" },
    unspsc: "47131803",
    categoryPath: "Janitorial & Cleaning > Floor Care > Concentrates",
    brand: "Diversey",
    mpn: "DIV-5271361",
    packSize: 1,
    packUnit: "per each",
    certifications: ["UL Listed"],
    contractTier: "Tier 1",
    preferredSupplier: true,
    co2PerUnit: 2.8,
    recycledContent: 0,
  },
  {
    id: "prod-02",
    name: "Eco Floor Cleaner Concentrate",
    description: "Plant-based neutral floor cleaner safe for all hard surfaces. Green Seal GS-37 certified. No harsh fumes.",
    unitOfMeasure: "Gallon",
    unitPrice: "21.00",
    supplier: "Network Distribution",
    contract: "OMNIA R-ND-JC-20003",
    availability: "In Stock",
    isEco: true,
    category: "Janitorial & Cleaning",
    specifications: { dilutionRatio: "1:64", ph: "7.0", color: "Clear", scent: "Lavender", bioBased: true },
    unspsc: "47131803",
    categoryPath: "Janitorial & Cleaning > Floor Care > Concentrates",
    brand: "Ecolab",
    mpn: "ECO-6100286",
    packSize: 1,
    packUnit: "per each",
    certifications: ["Green Seal GS-37", "EPA Safer Choice", "USDA BioPreferred"],
    contractTier: "Tier 1",
    preferredSupplier: true,
    co2PerUnit: 0.9,
    recycledContent: 30,
  },
  {
    id: "prod-03",
    name: "Microfiber Cleaning Cloths 16x16",
    description: "Professional-grade 300 GSM split microfiber cloths. Machine washable up to 500 cycles. Color-coded for cross-contamination prevention.",
    unitOfMeasure: "Pack",
    unitPrice: "24.99",
    supplier: "Network Distribution",
    contract: "OMNIA R-ND-JC-20003",
    availability: "In Stock",
    isEco: false,
    category: "Janitorial & Cleaning",
    specifications: { size: "16x16 in", gsm: 300, material: "Split Microfiber", colors: "Blue/Green/Red/Yellow" },
    unspsc: "47131502",
    categoryPath: "Janitorial & Cleaning > Wipers & Cloths > Microfiber",
    brand: "Rubbermaid",
    mpn: "RUB-1820583",
    packSize: 12,
    packUnit: "per pack",
    certifications: [],
    contractTier: "Tier 1",
    preferredSupplier: true,
    co2PerUnit: 0.6,
    recycledContent: 20,
  },
  {
    id: "prod-04",
    name: "Microfiber Cleaning Cloths 16x16 Economy",
    description: "Economy microfiber cloths 250 GSM. Suitable for general-purpose wiping and dusting tasks.",
    unitOfMeasure: "Pack",
    unitPrice: "18.75",
    supplier: "Grainger",
    contract: null,
    availability: "In Stock",
    isEco: false,
    category: "Janitorial & Cleaning",
    specifications: { size: "16x16 in", gsm: 250, material: "Microfiber", colors: "Blue" },
    unspsc: "47131502",
    categoryPath: "Janitorial & Cleaning > Wipers & Cloths > Microfiber",
    brand: "Grainger Approved",
    mpn: "GRA-36MV04",
    packSize: 24,
    packUnit: "per case",
    certifications: [],
    contractTier: null,
    preferredSupplier: false,
    co2PerUnit: 0.8,
    recycledContent: 0,
  },
  {
    id: "prod-05",
    name: "Disinfectant Spray Quaternary 32oz",
    description: "EPA-registered quaternary ammonium disinfectant spray. Kills 99.9% of bacteria. 10-minute contact time.",
    unitOfMeasure: "Each",
    unitPrice: "4.89",
    supplier: "Network Distribution",
    contract: "OMNIA R-ND-JC-20003",
    availability: "In Stock",
    isEco: false,
    category: "Janitorial & Cleaning",
    specifications: { volume: "32 oz", activeIngredient: "Quaternary Ammonium", contactTime: "10 min", epaReg: "1839-169" },
    unspsc: "47131810",
    categoryPath: "Janitorial & Cleaning > Disinfectants > Spray",
    brand: "Diversey",
    mpn: "DIV-04743",
    packSize: 1,
    packUnit: "per each",
    certifications: ["EPA Registered"],
    contractTier: "Tier 2",
    preferredSupplier: false,
    co2PerUnit: 1.2,
    recycledContent: 0,
  },
  {
    id: "prod-06",
    name: "Disinfectant Spray Hydrogen Peroxide 32oz",
    description: "Hydrogen peroxide-based disinfectant spray. No harsh fumes, no rinse required on food-contact surfaces.",
    unitOfMeasure: "Each",
    unitPrice: "5.49",
    supplier: "Network Distribution",
    contract: "OMNIA R-ND-JC-20003",
    availability: "In Stock",
    isEco: true,
    category: "Janitorial & Cleaning",
    specifications: { volume: "32 oz", activeIngredient: "Hydrogen Peroxide 3%", contactTime: "5 min", epaReg: "70627-56" },
    unspsc: "47131810",
    categoryPath: "Janitorial & Cleaning > Disinfectants > Spray",
    brand: "Ecolab",
    mpn: "ECO-6100286",
    packSize: 1,
    packUnit: "per each",
    certifications: ["EPA Safer Choice", "Green Seal GS-37"],
    contractTier: "Tier 1",
    preferredSupplier: true,
    co2PerUnit: 0.5,
    recycledContent: 25,
  },
  {
    id: "prod-07",
    name: "Industrial Wet Mop Head Cotton #24",
    description: "Heavy-duty 4-ply cotton cut-end wet mop head. 24 oz. Fits standard 5 in headband.",
    unitOfMeasure: "Each",
    unitPrice: "8.50",
    supplier: "Grainger",
    contract: "OMNIA R-GR-JC-20001",
    availability: "Low Stock",
    isEco: false,
    category: "Janitorial & Cleaning",
    specifications: { weight: "24 oz", material: "4-Ply Cotton", headband: "5 in", type: "Cut End" },
    unspsc: "47131604",
    categoryPath: "Janitorial & Cleaning > Mops & Accessories > Wet Mop Heads",
    brand: "Rubbermaid",
    mpn: "RUB-FGV11900",
    packSize: 1,
    packUnit: "per each",
    certifications: [],
    contractTier: "Tier 1",
    preferredSupplier: true,
    co2PerUnit: 1.4,
    recycledContent: 0,
  },
  {
    id: "prod-08",
    name: "Industrial Wet Mop Head Blend #24",
    description: "Cotton/synthetic blend looped-end wet mop. Lasts 3x longer than cut-end. Launderable.",
    unitOfMeasure: "Each",
    unitPrice: "8.75",
    supplier: "Network Distribution",
    contract: "OMNIA R-ND-JC-20003",
    availability: "In Stock",
    isEco: false,
    category: "Janitorial & Cleaning",
    specifications: { weight: "24 oz", material: "Cotton/Synthetic Blend", headband: "5 in", type: "Looped End" },
    unspsc: "47131604",
    categoryPath: "Janitorial & Cleaning > Mops & Accessories > Wet Mop Heads",
    brand: "Rubbermaid",
    mpn: "RUB-FGA15306",
    packSize: 1,
    packUnit: "per each",
    certifications: [],
    contractTier: "Tier 2",
    preferredSupplier: false,
    co2PerUnit: 1.1,
    recycledContent: 15,
  },
  {
    id: "prod-09",
    name: "Trash Can Liners 55 Gallon Black Heavy-Duty",
    description: "Heavy-duty 2 mil low-density polyethylene trash liners. Star-sealed bottom prevents leaks.",
    unitOfMeasure: "Case",
    unitPrice: "45.00",
    supplier: "Global Industrial",
    contract: "OMNIA R-GI-NS-21004",
    availability: "In Stock",
    isEco: false,
    category: "Janitorial & Cleaning",
    specifications: { capacity: "55 gal", mil: 2.0, material: "LDPE", color: "Black", sealType: "Star Seal" },
    unspsc: "47121701",
    categoryPath: "Janitorial & Cleaning > Waste Management > Trash Liners",
    brand: "Heritage",
    mpn: "HER-H8053TK",
    packSize: 100,
    packUnit: "per case",
    certifications: [],
    contractTier: "Tier 1",
    preferredSupplier: true,
    co2PerUnit: 3.5,
    recycledContent: 0,
  },
  {
    id: "prod-10",
    name: "Trash Can Liners 55 Gallon Eco Recycled",
    description: "Recycled content (80%) trash liners. 1.5 mil LLDPE with reinforced gusset seams.",
    unitOfMeasure: "Case",
    unitPrice: "47.50",
    supplier: "Network Distribution",
    contract: "OMNIA R-ND-JC-20003",
    availability: "In Stock",
    isEco: true,
    category: "Janitorial & Cleaning",
    specifications: { capacity: "55 gal", mil: 1.5, material: "Recycled LLDPE", color: "Black", sealType: "Gusset" },
    unspsc: "47121701",
    categoryPath: "Janitorial & Cleaning > Waste Management > Trash Liners",
    brand: "EarthSense",
    mpn: "ESE-RNW5815",
    packSize: 100,
    packUnit: "per case",
    certifications: ["EPA CPG", "Green Seal GS-37"],
    contractTier: "Tier 2",
    preferredSupplier: false,
    co2PerUnit: 1.2,
    recycledContent: 80,
  },

  // ═══════════════════════════════════════════
  // OFFICE SUPPLIES (~10 products)
  // ═══════════════════════════════════════════
  {
    id: "prod-11",
    name: "Multi-Purpose Copy Paper 8.5x11 20lb",
    description: "Bright white 92-brightness copy paper. Acid-free for archival quality. Works in laser and inkjet printers.",
    unitOfMeasure: "Case",
    unitPrice: "42.99",
    supplier: "ODP Business Solutions",
    contract: "OMNIA R-OD-OS-20010",
    availability: "In Stock",
    isEco: false,
    category: "Office Supplies",
    specifications: { size: "8.5x11 in", weight: "20 lb", brightness: 92, sheetsPerReam: 500 },
    unspsc: "44121506",
    categoryPath: "Office Supplies > Paper > Copy & Multi-Purpose",
    brand: "Hammermill",
    mpn: "HAM-86700",
    packSize: 10,
    packUnit: "per case (10 reams)",
    certifications: ["SFI Certified"],
    contractTier: "Tier 1",
    preferredSupplier: true,
    co2PerUnit: 4.2,
    recycledContent: 0,
  },
  {
    id: "prod-12",
    name: "100% Recycled Copy Paper 8.5x11 20lb",
    description: "100% post-consumer recycled copy paper. 92-brightness, acid-free. FSC and Green Seal certified.",
    unitOfMeasure: "Case",
    unitPrice: "46.50",
    supplier: "ODP Business Solutions",
    contract: "OMNIA R-OD-OS-20010",
    availability: "In Stock",
    isEco: true,
    category: "Office Supplies",
    specifications: { size: "8.5x11 in", weight: "20 lb", brightness: 92, sheetsPerReam: 500, postConsumer: "100%" },
    unspsc: "44121506",
    categoryPath: "Office Supplies > Paper > Copy & Multi-Purpose",
    brand: "Boise ASPEN",
    mpn: "CAS-054901",
    packSize: 10,
    packUnit: "per case (10 reams)",
    certifications: ["FSC Certified", "Green Seal GS-07", "EPA CPG"],
    contractTier: "Tier 1",
    preferredSupplier: true,
    co2PerUnit: 2.1,
    recycledContent: 100,
  },
  {
    id: "prod-13",
    name: "Ballpoint Pens Medium Point Blue 12-Pack",
    description: "Retractable ballpoint pens with comfort grip. 1.0mm medium point, smooth ink flow.",
    unitOfMeasure: "Box",
    unitPrice: "8.49",
    supplier: "ODP Business Solutions",
    contract: "OMNIA R-OD-OS-20010",
    availability: "In Stock",
    isEco: false,
    category: "Office Supplies",
    specifications: { pointSize: "1.0mm", inkColor: "Blue", type: "Retractable", grip: "Rubber" },
    unspsc: "44121704",
    categoryPath: "Office Supplies > Writing Instruments > Ballpoint Pens",
    brand: "Pilot",
    mpn: "PIL-32011",
    packSize: 12,
    packUnit: "per box",
    certifications: [],
    contractTier: "Tier 1",
    preferredSupplier: true,
    co2PerUnit: 0.3,
    recycledContent: 0,
  },
  {
    id: "prod-14",
    name: "Recycled Ballpoint Pens Medium Point Blue 12-Pack",
    description: "Retractable pens made from 83% recycled plastic bottles (B2P). 1.0mm medium point.",
    unitOfMeasure: "Box",
    unitPrice: "9.25",
    supplier: "Quill",
    contract: "OMNIA R-QU-OS-20012",
    availability: "In Stock",
    isEco: true,
    category: "Office Supplies",
    specifications: { pointSize: "1.0mm", inkColor: "Blue", type: "Retractable", grip: "Rubber", recycledPlastic: "83%" },
    unspsc: "44121704",
    categoryPath: "Office Supplies > Writing Instruments > Ballpoint Pens",
    brand: "Pilot B2P",
    mpn: "PIL-32801",
    packSize: 12,
    packUnit: "per box",
    certifications: ["EPA CPG"],
    contractTier: "Tier 2",
    preferredSupplier: false,
    co2PerUnit: 0.15,
    recycledContent: 83,
  },
  {
    id: "prod-15",
    name: "Manila File Folders Letter 1/3 Tab",
    description: "Standard manila file folders with 1/3 cut assorted tab positions. 11pt stock.",
    unitOfMeasure: "Box",
    unitPrice: "12.99",
    supplier: "ODP Business Solutions",
    contract: "OMNIA R-OD-OS-20010",
    availability: "In Stock",
    isEco: false,
    category: "Office Supplies",
    specifications: { size: "Letter", tabCut: "1/3", stock: "11pt", color: "Manila" },
    unspsc: "44122003",
    categoryPath: "Office Supplies > Filing & Storage > File Folders",
    brand: "Smead",
    mpn: "SMD-10330",
    packSize: 100,
    packUnit: "per box",
    certifications: ["SFI Certified"],
    contractTier: "Tier 1",
    preferredSupplier: true,
    co2PerUnit: 1.5,
    recycledContent: 10,
  },
  {
    id: "prod-16",
    name: "Invisible Tape 3/4in x 1000in",
    description: "Matte finish invisible tape. Won't show on copies. Repositionable up to 20 seconds after application.",
    unitOfMeasure: "Roll",
    unitPrice: "3.29",
    supplier: "Quill",
    contract: "OMNIA R-QU-OS-20012",
    availability: "Low Stock",
    isEco: false,
    category: "Office Supplies",
    specifications: { width: "3/4 in", length: "1000 in", core: "1 in", finish: "Matte" },
    unspsc: "44111515",
    categoryPath: "Office Supplies > Tape & Adhesives > Invisible Tape",
    brand: "3M Scotch",
    mpn: "MMM-810",
    packSize: 1,
    packUnit: "per each",
    certifications: [],
    contractTier: "Tier 1",
    preferredSupplier: false,
    co2PerUnit: 0.2,
    recycledContent: 0,
  },
  {
    id: "prod-17",
    name: "Shipping Labels 2x4 White 1000ct",
    description: "Permanent adhesive white shipping labels for laser and inkjet printers. Easy peel backing.",
    unitOfMeasure: "Box",
    unitPrice: "22.50",
    supplier: "Quill",
    contract: "OMNIA R-QU-OS-20012",
    availability: "In Stock",
    isEco: false,
    category: "Office Supplies",
    specifications: { size: "2x4 in", labelsPerSheet: 10, sheetsPerBox: 100, adhesive: "Permanent" },
    unspsc: "44102802",
    categoryPath: "Office Supplies > Labels & Stickers > Shipping Labels",
    brand: "Avery",
    mpn: "AVE-5163",
    packSize: 1,
    packUnit: "per box (1000 labels)",
    certifications: [],
    contractTier: "Tier 2",
    preferredSupplier: false,
    co2PerUnit: 0.7,
    recycledContent: 0,
  },
  {
    id: "prod-18",
    name: "3-Ring Binder 1.5in View White",
    description: "Heavy-duty D-ring view binder with clear overlay cover. 1.5 inch capacity holds approximately 375 sheets.",
    unitOfMeasure: "Each",
    unitPrice: "6.49",
    supplier: "ODP Business Solutions",
    contract: "OMNIA R-OD-OS-20010",
    availability: "In Stock",
    isEco: false,
    category: "Office Supplies",
    specifications: { ringSize: "1.5 in", ringType: "D-Ring", capacity: "375 sheets", color: "White" },
    unspsc: "44122104",
    categoryPath: "Office Supplies > Binders & Accessories > View Binders",
    brand: "Avery",
    mpn: "AVE-79195",
    packSize: 1,
    packUnit: "per each",
    certifications: [],
    contractTier: "Tier 2",
    preferredSupplier: true,
    co2PerUnit: 0.9,
    recycledContent: 0,
  },
  {
    id: "prod-19",
    name: "Sticky Notes 3x3 Yellow 12-Pack",
    description: "Classic yellow self-stick notes. Repositionable adhesive. 100 sheets per pad.",
    unitOfMeasure: "Pack",
    unitPrice: "11.49",
    supplier: "ODP Business Solutions",
    contract: "OMNIA R-OD-OS-20010",
    availability: "In Stock",
    isEco: false,
    category: "Office Supplies",
    specifications: { size: "3x3 in", sheetsPerPad: 100, color: "Canary Yellow" },
    unspsc: "44112005",
    categoryPath: "Office Supplies > Sticky Notes & Flags > Sticky Notes",
    brand: "3M Post-it",
    mpn: "MMM-654",
    packSize: 12,
    packUnit: "per pack",
    certifications: [],
    contractTier: "Tier 1",
    preferredSupplier: true,
    co2PerUnit: 0.4,
    recycledContent: 0,
  },
  {
    id: "prod-20",
    name: "Recycled Sticky Notes 3x3 Yellow 12-Pack",
    description: "Sticky notes made from 100% recycled paper. Same repositionable adhesive as original.",
    unitOfMeasure: "Pack",
    unitPrice: "12.99",
    supplier: "Quill",
    contract: "OMNIA R-QU-OS-20012",
    availability: "In Stock",
    isEco: true,
    category: "Office Supplies",
    specifications: { size: "3x3 in", sheetsPerPad: 100, color: "Canary Yellow", recycled: true },
    unspsc: "44112005",
    categoryPath: "Office Supplies > Sticky Notes & Flags > Sticky Notes",
    brand: "3M Post-it Greener",
    mpn: "MMM-654RP",
    packSize: 12,
    packUnit: "per pack",
    certifications: ["SFI Certified", "EPA CPG"],
    contractTier: "Tier 2",
    preferredSupplier: false,
    co2PerUnit: 0.2,
    recycledContent: 100,
  },

  // ═══════════════════════════════════════════
  // SAFETY & PPE (~8 products)
  // ═══════════════════════════════════════════
  {
    id: "prod-21",
    name: "Nitrile Exam Gloves Powder-Free Medium",
    description: "Disposable nitrile exam gloves. 4 mil thickness. Textured fingertips for enhanced grip. Latex-free.",
    unitOfMeasure: "Box",
    unitPrice: "14.99",
    supplier: "Safeware",
    contract: "OMNIA R-SW-SP-22003",
    availability: "In Stock",
    isEco: false,
    category: "Safety & PPE",
    specifications: { material: "Nitrile", thickness: "4 mil", size: "Medium", powderFree: true, latexFree: true },
    unspsc: "46181504",
    categoryPath: "Safety & PPE > Hand Protection > Disposable Gloves",
    brand: "Kimberly-Clark",
    mpn: "KCC-55082",
    packSize: 100,
    packUnit: "per box",
    certifications: ["FDA 510k", "ASTM D6319"],
    contractTier: "Tier 1",
    preferredSupplier: true,
    co2PerUnit: 1.8,
    recycledContent: 0,
  },
  {
    id: "prod-22",
    name: "Nitrile Exam Gloves Powder-Free Medium Economy",
    description: "Economy disposable nitrile gloves. 3.5 mil thickness. Beaded cuff. Good dexterity.",
    unitOfMeasure: "Box",
    unitPrice: "11.50",
    supplier: "MSC Industrial",
    contract: null,
    availability: "In Stock",
    isEco: false,
    category: "Safety & PPE",
    specifications: { material: "Nitrile", thickness: "3.5 mil", size: "Medium", powderFree: true, latexFree: true },
    unspsc: "46181504",
    categoryPath: "Safety & PPE > Hand Protection > Disposable Gloves",
    brand: "MedPride",
    mpn: "MDP-NIT200M",
    packSize: 100,
    packUnit: "per box",
    certifications: ["FDA 510k"],
    contractTier: null,
    preferredSupplier: false,
    co2PerUnit: 2.1,
    recycledContent: 0,
  },
  {
    id: "prod-23",
    name: "Safety Goggles Splash-Proof Over-Glasses",
    description: "Indirect-vent chemical splash goggles. Fits over prescription glasses. Anti-fog polycarbonate lens.",
    unitOfMeasure: "Each",
    unitPrice: "7.25",
    supplier: "Grainger",
    contract: "OMNIA R-GR-JC-20001",
    availability: "In Stock",
    isEco: false,
    category: "Safety & PPE",
    specifications: { lensType: "Polycarbonate", antiFog: true, ventType: "Indirect", overGlasses: true },
    unspsc: "46181802",
    categoryPath: "Safety & PPE > Eye Protection > Goggles",
    brand: "3M",
    mpn: "MMM-16645",
    packSize: 1,
    packUnit: "per each",
    certifications: ["ANSI Z87.1", "CSA Z94.3"],
    contractTier: "Tier 1",
    preferredSupplier: true,
    co2PerUnit: 0.5,
    recycledContent: 0,
  },
  {
    id: "prod-24",
    name: "High-Visibility Safety Vest Class 2",
    description: "ANSI Class 2 high-visibility mesh safety vest. Two-tone reflective striping. Zipper closure.",
    unitOfMeasure: "Each",
    unitPrice: "12.75",
    supplier: "MSC Industrial",
    contract: "OMNIA R-MS-SP-21008",
    availability: "In Stock",
    isEco: false,
    category: "Safety & PPE",
    specifications: { class: "ANSI Class 2", material: "Polyester Mesh", closure: "Zipper", color: "Lime Green" },
    unspsc: "46181540",
    categoryPath: "Safety & PPE > Hi-Vis Apparel > Safety Vests",
    brand: "Ergodyne",
    mpn: "ERG-8210HL",
    packSize: 1,
    packUnit: "per each",
    certifications: ["ANSI/ISEA 107-2020"],
    contractTier: "Tier 2",
    preferredSupplier: false,
    co2PerUnit: 0.7,
    recycledContent: 0,
  },
  {
    id: "prod-25",
    name: "Cut-Resistant Work Gloves Level A4",
    description: "ANSI A4 cut-resistant knit gloves with polyurethane palm coating. Touchscreen compatible.",
    unitOfMeasure: "Pair",
    unitPrice: "9.99",
    supplier: "MSC Industrial",
    contract: "OMNIA R-MS-SP-21008",
    availability: "In Stock",
    isEco: false,
    category: "Safety & PPE",
    specifications: { cutLevel: "ANSI A4", coating: "Polyurethane", material: "HPPE", touchscreen: true },
    unspsc: "46181508",
    categoryPath: "Safety & PPE > Hand Protection > Cut-Resistant Gloves",
    brand: "Ansell",
    mpn: "ANS-11-735",
    packSize: 1,
    packUnit: "per pair",
    certifications: ["ANSI/ISEA 105-2016", "EN 388:2016"],
    contractTier: "Tier 2",
    preferredSupplier: false,
    co2PerUnit: 0.6,
    recycledContent: 0,
  },
  {
    id: "prod-26",
    name: "Disposable Foam Ear Plugs 32dB NRR",
    description: "Tapered PVC foam ear plugs. 32dB noise reduction rating. Individually wrapped pairs.",
    unitOfMeasure: "Box",
    unitPrice: "22.50",
    supplier: "MSC Industrial",
    contract: "OMNIA R-MS-SP-21008",
    availability: "In Stock",
    isEco: false,
    category: "Safety & PPE",
    specifications: { nrr: "32 dB", material: "PVC Foam", type: "Tapered", wrapped: true },
    unspsc: "46181606",
    categoryPath: "Safety & PPE > Hearing Protection > Ear Plugs",
    brand: "3M E-A-R",
    mpn: "MMM-312-1250",
    packSize: 200,
    packUnit: "per box",
    certifications: ["ANSI S3.19"],
    contractTier: "Tier 1",
    preferredSupplier: true,
    co2PerUnit: 0.3,
    recycledContent: 0,
  },
  {
    id: "prod-27",
    name: "Hard Hat Type I Class E White",
    description: "Ratchet suspension hard hat. Type I Class E electrical rated. 4-point suspension. UV resistant.",
    unitOfMeasure: "Each",
    unitPrice: "18.99",
    supplier: "Safeware",
    contract: "OMNIA R-SW-SP-22003",
    availability: "In Stock",
    isEco: false,
    category: "Safety & PPE",
    specifications: { type: "Type I", class: "Class E", suspension: "4-Point Ratchet", color: "White" },
    unspsc: "46181701",
    categoryPath: "Safety & PPE > Head Protection > Hard Hats",
    brand: "Honeywell",
    mpn: "HON-A59010000",
    packSize: 1,
    packUnit: "per each",
    certifications: ["ANSI Z89.1", "CSA Z94.1"],
    contractTier: "Tier 1",
    preferredSupplier: true,
    co2PerUnit: 1.2,
    recycledContent: 0,
  },
  {
    id: "prod-28",
    name: "Hard Hat Type I Class E White Economy",
    description: "Pin-lock suspension hard hat. Type I Class E. Standard 4-point suspension. Budget option.",
    unitOfMeasure: "Each",
    unitPrice: "11.49",
    supplier: "Grainger",
    contract: null,
    availability: "In Stock",
    isEco: false,
    category: "Safety & PPE",
    specifications: { type: "Type I", class: "Class E", suspension: "4-Point Pin-Lock", color: "White" },
    unspsc: "46181701",
    categoryPath: "Safety & PPE > Head Protection > Hard Hats",
    brand: "MSA",
    mpn: "MSA-475358",
    packSize: 1,
    packUnit: "per each",
    certifications: ["ANSI Z89.1"],
    contractTier: null,
    preferredSupplier: false,
    co2PerUnit: 1.4,
    recycledContent: 0,
  },

  // ═══════════════════════════════════════════
  // BREAKROOM & FOOD SERVICE (~8 products)
  // ═══════════════════════════════════════════
  {
    id: "prod-29",
    name: "Hot Cups 12oz Paper White",
    description: "Single-wall paper hot cups with polyethylene lining. Compatible with standard dome lids.",
    unitOfMeasure: "Case",
    unitPrice: "58.00",
    supplier: "ODP Business Solutions",
    contract: "OMNIA R-OD-OS-20010",
    availability: "In Stock",
    isEco: false,
    category: "Breakroom & Food Service",
    specifications: { size: "12 oz", material: "Poly-lined Paper", color: "White", lidCompatible: true },
    unspsc: "52151504",
    categoryPath: "Breakroom & Food Service > Cups & Lids > Hot Cups",
    brand: "Solo",
    mpn: "SOL-412WN",
    packSize: 1000,
    packUnit: "per case",
    certifications: [],
    contractTier: "Tier 1",
    preferredSupplier: true,
    co2PerUnit: 4.5,
    recycledContent: 0,
  },
  {
    id: "prod-30",
    name: "Hot Cups 12oz Compostable PLA",
    description: "Plant-based PLA-lined compostable hot cups. BPI certified compostable in commercial facilities.",
    unitOfMeasure: "Case",
    unitPrice: "72.00",
    supplier: "ODP Business Solutions",
    contract: "OMNIA R-OD-OS-20010",
    availability: "In Stock",
    isEco: true,
    category: "Breakroom & Food Service",
    specifications: { size: "12 oz", material: "PLA-lined Paper", color: "Kraft", lidCompatible: true, compostable: true },
    unspsc: "52151504",
    categoryPath: "Breakroom & Food Service > Cups & Lids > Hot Cups",
    brand: "World Centric",
    mpn: "WCC-CUPA12",
    packSize: 1000,
    packUnit: "per case",
    certifications: ["BPI Certified", "FSC Certified"],
    contractTier: "Tier 2",
    preferredSupplier: false,
    co2PerUnit: 1.8,
    recycledContent: 0,
  },
  {
    id: "prod-31",
    name: "Beverage Napkins 1-Ply White",
    description: "Standard 1-ply beverage napkins. Embossed texture. Quarter fold.",
    unitOfMeasure: "Case",
    unitPrice: "28.99",
    supplier: "ODP Business Solutions",
    contract: "OMNIA R-OD-OS-20010",
    availability: "In Stock",
    isEco: false,
    category: "Breakroom & Food Service",
    specifications: { ply: 1, size: "9.5x9.5 in folded", color: "White", fold: "Quarter" },
    unspsc: "52151502",
    categoryPath: "Breakroom & Food Service > Napkins & Tissues > Beverage Napkins",
    brand: "GP Pro",
    mpn: "GPC-96019",
    packSize: 4000,
    packUnit: "per case",
    certifications: [],
    contractTier: "Tier 1",
    preferredSupplier: true,
    co2PerUnit: 2.0,
    recycledContent: 0,
  },
  {
    id: "prod-32",
    name: "Premium Ground Coffee Medium Roast Fraction Packs",
    description: "100% Arabica medium roast ground coffee. Individually packaged fraction packs for commercial brewers.",
    unitOfMeasure: "Case",
    unitPrice: "64.99",
    supplier: "ODP Business Solutions",
    contract: "OMNIA R-OD-OS-20010",
    availability: "In Stock",
    isEco: false,
    category: "Breakroom & Food Service",
    specifications: { roast: "Medium", type: "Ground", bean: "100% Arabica", packWeight: "2 oz each" },
    unspsc: "50201706",
    categoryPath: "Breakroom & Food Service > Coffee & Tea > Ground Coffee",
    brand: "Folgers",
    mpn: "FOL-06114",
    packSize: 42,
    packUnit: "per case",
    certifications: [],
    contractTier: "Tier 2",
    preferredSupplier: false,
    co2PerUnit: 3.0,
    recycledContent: 0,
  },
  {
    id: "prod-33",
    name: "Fair Trade Organic Coffee Medium Roast",
    description: "USDA Organic and Fair Trade certified medium roast. Shade-grown single origin. Fraction packs.",
    unitOfMeasure: "Case",
    unitPrice: "79.99",
    supplier: "Quill",
    contract: null,
    availability: "In Stock",
    isEco: true,
    category: "Breakroom & Food Service",
    specifications: { roast: "Medium", type: "Ground", bean: "100% Arabica", packWeight: "2 oz each", origin: "Colombia" },
    unspsc: "50201706",
    categoryPath: "Breakroom & Food Service > Coffee & Tea > Ground Coffee",
    brand: "Green Mountain",
    mpn: "GMT-6520",
    packSize: 42,
    packUnit: "per case",
    certifications: ["USDA Organic", "Fair Trade Certified"],
    contractTier: null,
    preferredSupplier: false,
    co2PerUnit: 1.5,
    recycledContent: 0,
  },
  {
    id: "prod-34",
    name: "Granulated White Sugar Packets",
    description: "Individual serving packets of granulated cane sugar. 2.83g per packet.",
    unitOfMeasure: "Box",
    unitPrice: "8.49",
    supplier: "ODP Business Solutions",
    contract: "OMNIA R-OD-OS-20010",
    availability: "In Stock",
    isEco: false,
    category: "Breakroom & Food Service",
    specifications: { weight: "2.83g per packet", type: "Granulated Cane", individual: true },
    unspsc: "50161509",
    categoryPath: "Breakroom & Food Service > Condiments & Sweeteners > Sugar",
    brand: "Domino",
    mpn: "DOM-QUIK-STIK",
    packSize: 2000,
    packUnit: "per box",
    certifications: [],
    contractTier: "Tier 1",
    preferredSupplier: true,
    co2PerUnit: 0.5,
    recycledContent: 0,
  },
  {
    id: "prod-35",
    name: "Paper Towel Rolls C-Fold White",
    description: "C-fold paper towels for universal dispensers. 1-ply absorbent white.",
    unitOfMeasure: "Case",
    unitPrice: "42.50",
    supplier: "ODP Business Solutions",
    contract: "OMNIA R-OD-OS-20010",
    availability: "In Stock",
    isEco: false,
    category: "Breakroom & Food Service",
    specifications: { fold: "C-Fold", ply: 1, color: "White", sheetsPerPack: 200 },
    unspsc: "14111703",
    categoryPath: "Breakroom & Food Service > Paper Towels > Folded Towels",
    brand: "Kimberly-Clark",
    mpn: "KCC-01510",
    packSize: 2400,
    packUnit: "per case (12 packs)",
    certifications: [],
    contractTier: "Tier 1",
    preferredSupplier: true,
    co2PerUnit: 3.2,
    recycledContent: 0,
  },
  {
    id: "prod-36",
    name: "Foam Plates 9in White",
    description: "Disposable foam plates. Sturdy construction resists cuts and soak-through. Microwave safe.",
    unitOfMeasure: "Case",
    unitPrice: "32.99",
    supplier: "ODP Business Solutions",
    contract: "OMNIA R-OD-OS-20010",
    availability: "Low Stock",
    isEco: false,
    category: "Breakroom & Food Service",
    specifications: { size: "9 in", material: "Polystyrene Foam", color: "White", microwaveSafe: true },
    unspsc: "52151505",
    categoryPath: "Breakroom & Food Service > Plates & Bowls > Foam Plates",
    brand: "Dart",
    mpn: "DCC-9PWQ",
    packSize: 500,
    packUnit: "per case",
    certifications: [],
    contractTier: "Tier 2",
    preferredSupplier: false,
    co2PerUnit: 2.8,
    recycledContent: 0,
  },

  // ═══════════════════════════════════════════
  // FACILITY MAINTENANCE & MRO (~8 products)
  // ═══════════════════════════════════════════
  {
    id: "prod-37",
    name: "HVAC Pleated Air Filter 20x25x1 MERV 8",
    description: "Standard pleated air filter for commercial HVAC systems. MERV 8 rated. Electrostatically charged media.",
    unitOfMeasure: "Case",
    unitPrice: "72.00",
    supplier: "Grainger",
    contract: "OMNIA R-GR-JC-20001",
    availability: "In Stock",
    isEco: false,
    category: "Facility Maintenance & MRO",
    specifications: { size: "20x25x1 in", merv: 8, media: "Synthetic Pleated", frame: "Beverage Board" },
    unspsc: "40161505",
    categoryPath: "Facility Maintenance & MRO > HVAC & Refrigeration > Air Filters",
    brand: "3M Filtrete",
    mpn: "MMM-9830DC-6",
    packSize: 12,
    packUnit: "per case",
    certifications: ["UL Listed"],
    contractTier: "Tier 1",
    preferredSupplier: true,
    co2PerUnit: 2.5,
    recycledContent: 0,
  },
  {
    id: "prod-38",
    name: "HVAC Pleated Air Filter 20x25x1 MERV 11",
    description: "High-efficiency pleated air filter. MERV 11 rated captures allergens, mold spores, and fine dust.",
    unitOfMeasure: "Case",
    unitPrice: "89.00",
    supplier: "Lawson Products",
    contract: "OMNIA R-LP-MR-21006",
    availability: "In Stock",
    isEco: false,
    category: "Facility Maintenance & MRO",
    specifications: { size: "20x25x1 in", merv: 11, media: "Synthetic Pleated", frame: "Beverage Board" },
    unspsc: "40161505",
    categoryPath: "Facility Maintenance & MRO > HVAC & Refrigeration > Air Filters",
    brand: "3M Filtrete",
    mpn: "MMM-9831DC-6",
    packSize: 12,
    packUnit: "per case",
    certifications: ["UL Listed"],
    contractTier: "Tier 1",
    preferredSupplier: false,
    co2PerUnit: 2.8,
    recycledContent: 0,
  },
  {
    id: "prod-39",
    name: "AA Alkaline Batteries 24-Pack",
    description: "Industrial-grade AA alkaline batteries. 10-year shelf life. For high-drain devices.",
    unitOfMeasure: "Pack",
    unitPrice: "16.99",
    supplier: "Lawson Products",
    contract: "OMNIA R-LP-MR-21006",
    availability: "In Stock",
    isEco: false,
    category: "Facility Maintenance & MRO",
    specifications: { size: "AA", chemistry: "Alkaline", voltage: "1.5V", shelfLife: "10 years" },
    unspsc: "26111702",
    categoryPath: "Facility Maintenance & MRO > Batteries & Power > Alkaline Batteries",
    brand: "Duracell Procell",
    mpn: "DUR-PC1500BKD",
    packSize: 24,
    packUnit: "per pack",
    certifications: [],
    contractTier: "Tier 1",
    preferredSupplier: true,
    co2PerUnit: 0.8,
    recycledContent: 0,
  },
  {
    id: "prod-40",
    name: "AA Alkaline Batteries 48-Pack",
    description: "Bulk pack industrial AA alkaline batteries. Same Procell quality, better per-unit value.",
    unitOfMeasure: "Pack",
    unitPrice: "29.99",
    supplier: "Grainger",
    contract: "OMNIA R-GR-JC-20001",
    availability: "In Stock",
    isEco: false,
    category: "Facility Maintenance & MRO",
    specifications: { size: "AA", chemistry: "Alkaline", voltage: "1.5V", shelfLife: "10 years" },
    unspsc: "26111702",
    categoryPath: "Facility Maintenance & MRO > Batteries & Power > Alkaline Batteries",
    brand: "Duracell Procell",
    mpn: "DUR-PC1500BKD48",
    packSize: 48,
    packUnit: "per pack",
    certifications: [],
    contractTier: "Tier 1",
    preferredSupplier: true,
    co2PerUnit: 1.5,
    recycledContent: 0,
  },
  {
    id: "prod-41",
    name: "LED Tube T8 4ft 18W 5000K",
    description: "Direct-wire LED tube replacement for T8 fluorescent. 5000K daylight, 2200 lumens. Ballast bypass.",
    unitOfMeasure: "Case",
    unitPrice: "89.99",
    supplier: "Global Industrial",
    contract: "OMNIA R-GI-NS-21004",
    availability: "In Stock",
    isEco: true,
    category: "Facility Maintenance & MRO",
    specifications: { length: "4 ft", wattage: "18W", colorTemp: "5000K", lumens: 2200, type: "Ballast Bypass" },
    unspsc: "39101612",
    categoryPath: "Facility Maintenance & MRO > Lighting > LED Tubes",
    brand: "Philips",
    mpn: "PHI-541086",
    packSize: 25,
    packUnit: "per case",
    certifications: ["UL Listed", "DLC Qualified", "Energy Star"],
    contractTier: "Tier 1",
    preferredSupplier: true,
    co2PerUnit: 1.0,
    recycledContent: 0,
  },
  {
    id: "prod-42",
    name: "Foam Hand Soap Refill 1250mL",
    description: "Antibacterial foam hand soap dispenser refill. For commercial touchless dispensers. Light fragrance.",
    unitOfMeasure: "Case",
    unitPrice: "52.00",
    supplier: "Lawson Products",
    contract: "OMNIA R-LP-MR-21006",
    availability: "In Stock",
    isEco: false,
    category: "Facility Maintenance & MRO",
    specifications: { volume: "1250 mL", type: "Foam", antibacterial: true, dispenserCompatible: "GOJO LTX-12" },
    unspsc: "53131601",
    categoryPath: "Facility Maintenance & MRO > Restroom > Hand Soap",
    brand: "GOJO",
    mpn: "GOJ-1911-02",
    packSize: 2,
    packUnit: "per case",
    certifications: ["FDA OTC"],
    contractTier: "Tier 1",
    preferredSupplier: true,
    co2PerUnit: 1.5,
    recycledContent: 0,
  },
  {
    id: "prod-43",
    name: "Hand Truck Steel 600lb Capacity",
    description: "Heavy-duty steel hand truck with 600 lb capacity. Pneumatic tires. Continuous handle.",
    unitOfMeasure: "Each",
    unitPrice: "89.99",
    supplier: "Global Industrial",
    contract: "OMNIA R-GI-NS-21004",
    availability: "In Stock",
    isEco: false,
    category: "Facility Maintenance & MRO",
    specifications: { capacity: "600 lb", material: "Steel", tireType: "Pneumatic", handleType: "Continuous" },
    unspsc: "24101501",
    categoryPath: "Facility Maintenance & MRO > Material Handling > Hand Trucks",
    brand: "Global Industrial",
    mpn: "GBI-241655",
    packSize: 1,
    packUnit: "per each",
    certifications: [],
    contractTier: "Tier 2",
    preferredSupplier: false,
    co2PerUnit: 15.0,
    recycledContent: 30,
  },
  {
    id: "prod-44",
    name: "Multi-Purpose Lubricant Spray 11oz",
    description: "Penetrating lubricant and rust preventative. Displaces moisture, loosens frozen parts.",
    unitOfMeasure: "Each",
    unitPrice: "6.49",
    supplier: "Grainger",
    contract: "OMNIA R-GR-JC-20001",
    availability: "In Stock",
    isEco: false,
    category: "Facility Maintenance & MRO",
    specifications: { volume: "11 oz", type: "Aerosol", application: "Penetrant/Lubricant" },
    unspsc: "15121902",
    categoryPath: "Facility Maintenance & MRO > Lubricants & Adhesives > Penetrating Lubricants",
    brand: "WD-40",
    mpn: "WDF-490057",
    packSize: 1,
    packUnit: "per each",
    certifications: [],
    contractTier: "Tier 2",
    preferredSupplier: false,
    co2PerUnit: 1.8,
    recycledContent: 0,
  },

  // ═══════════════════════════════════════════
  // MEDICAL & LAB (~6 products)
  // ═══════════════════════════════════════════
  {
    id: "prod-45",
    name: "Nitrile Exam Gloves Powder-Free Medium Blue",
    description: "Medical-grade nitrile exam gloves. 3.5 mil chemo-rated. Textured fingertips. Beaded cuff.",
    unitOfMeasure: "Box",
    unitPrice: "12.99",
    supplier: "Medline",
    contract: "OMNIA R-MM-NR-20005",
    availability: "In Stock",
    isEco: false,
    category: "Medical & Lab",
    specifications: { material: "Nitrile", thickness: "3.5 mil", size: "Medium", chemoRated: true, color: "Blue" },
    unspsc: "42132203",
    categoryPath: "Medical & Lab > Exam Gloves > Nitrile Gloves",
    brand: "Medline",
    mpn: "MDS195285",
    packSize: 100,
    packUnit: "per box",
    certifications: ["FDA 510k", "ASTM D6319", "ASTM D6978 Chemo"],
    contractTier: "Tier 1",
    preferredSupplier: true,
    co2PerUnit: 1.6,
    recycledContent: 0,
  },
  {
    id: "prod-46",
    name: "N95 Disposable Respirator NIOSH-Approved",
    description: "NIOSH-approved N95 particulate respirator. Adjustable nose clip and braided headbands for secure fit.",
    unitOfMeasure: "Box",
    unitPrice: "18.99",
    supplier: "Medline",
    contract: "OMNIA R-MM-NR-20005",
    availability: "Low Stock",
    isEco: false,
    category: "Medical & Lab",
    specifications: { rating: "N95", type: "Cup", noseClip: "Adjustable Aluminum", exhalationValve: false },
    unspsc: "42131601",
    categoryPath: "Medical & Lab > Respiratory Protection > N95 Respirators",
    brand: "3M",
    mpn: "MMM-8210",
    packSize: 20,
    packUnit: "per box",
    certifications: ["NIOSH 42 CFR 84", "FDA Cleared"],
    contractTier: "Tier 1",
    preferredSupplier: true,
    co2PerUnit: 1.0,
    recycledContent: 0,
  },
  {
    id: "prod-47",
    name: "N95 Respirator Flat-Fold Economy",
    description: "Economy N95 respirator. Flat-fold design for easy storage. NIOSH approved.",
    unitOfMeasure: "Box",
    unitPrice: "14.50",
    supplier: "Safeware",
    contract: null,
    availability: "In Stock",
    isEco: false,
    category: "Medical & Lab",
    specifications: { rating: "N95", type: "Flat Fold", noseClip: "Foam Cushion", exhalationValve: false },
    unspsc: "42131601",
    categoryPath: "Medical & Lab > Respiratory Protection > N95 Respirators",
    brand: "Moldex",
    mpn: "MOL-2200N95",
    packSize: 20,
    packUnit: "per box",
    certifications: ["NIOSH 42 CFR 84"],
    contractTier: null,
    preferredSupplier: false,
    co2PerUnit: 1.3,
    recycledContent: 0,
  },
  {
    id: "prod-48",
    name: "First Aid Kit 50-Person ANSI A+",
    description: "Comprehensive 50-person first aid kit in wall-mountable metal case. ANSI A+ compliant with 245 items.",
    unitOfMeasure: "Each",
    unitPrice: "89.99",
    supplier: "Medline",
    contract: "OMNIA R-MM-NR-20005",
    availability: "In Stock",
    isEco: false,
    category: "Medical & Lab",
    specifications: { persons: 50, ansiClass: "A+", caseType: "Metal Wall Mount", items: 245 },
    unspsc: "42172001",
    categoryPath: "Medical & Lab > First Aid > First Aid Kits",
    brand: "First Aid Only",
    mpn: "FAO-90639",
    packSize: 1,
    packUnit: "per each",
    certifications: ["ANSI Z308.1-2021"],
    contractTier: "Tier 1",
    preferredSupplier: true,
    co2PerUnit: 3.2,
    recycledContent: 0,
  },
  {
    id: "prod-49",
    name: "Hand Sanitizer Gel 70% Alcohol 1L Pump",
    description: "Professional-grade ethyl alcohol hand sanitizer gel. Moisturizing formula with aloe vera. Pump bottle.",
    unitOfMeasure: "Each",
    unitPrice: "6.99",
    supplier: "Medline",
    contract: "OMNIA R-MM-NR-20005",
    availability: "In Stock",
    isEco: false,
    category: "Medical & Lab",
    specifications: { volume: "33.8 oz (1 L)", alcoholContent: "70%", type: "Gel", pumpIncluded: true },
    unspsc: "53131608",
    categoryPath: "Medical & Lab > Hand Hygiene > Sanitizers",
    brand: "GOJO Purell",
    mpn: "GOJ-3023-12",
    packSize: 1,
    packUnit: "per each",
    certifications: ["FDA OTC"],
    contractTier: "Tier 1",
    preferredSupplier: true,
    co2PerUnit: 0.8,
    recycledContent: 0,
  },
  {
    id: "prod-50",
    name: "Instant Cold Pack Single Use",
    description: "Disposable instant cold compress. Squeeze to activate. No refrigeration needed. 6x9 in.",
    unitOfMeasure: "Case",
    unitPrice: "34.99",
    supplier: "Medline",
    contract: "OMNIA R-MM-NR-20005",
    availability: "In Stock",
    isEco: false,
    category: "Medical & Lab",
    specifications: { size: "6x9 in", activationTime: "Instant squeeze", duration: "15-20 min" },
    unspsc: "42142901",
    categoryPath: "Medical & Lab > First Aid > Cold & Hot Therapy",
    brand: "Medline",
    mpn: "MDS137000",
    packSize: 24,
    packUnit: "per case",
    certifications: [],
    contractTier: "Tier 2",
    preferredSupplier: false,
    co2PerUnit: 0.4,
    recycledContent: 0,
  },
];

export async function ensureProductsSeeded() {
  const result = await db.select({ count: sql<number>`count(*)` }).from(products);
  const count = Number(result[0]?.count || 0);
  if (count >= sampleProducts.length) {
    return;
  }
  console.log(`Products table has ${count} rows, seeding ${sampleProducts.length} products...`);
  await db.delete(products);
  for (const product of sampleProducts) {
    await db.insert(products).values(product);
  }
  console.log(`Seeding complete! ${sampleProducts.length} products inserted.`);
}

async function seed() {
  console.log("Seeding database with OPUS-aligned catalog...");
  await db.delete(products);
  for (const product of sampleProducts) {
    await db.insert(products).values(product);
    console.log(`Inserted: ${product.name} (${product.id}) — ${product.supplier}`);
  }
  console.log(`Seeding complete! ${sampleProducts.length} products inserted.`);
}

const isDirectRun = process.argv[1]?.endsWith('seed.ts') || process.argv[1]?.endsWith('seed.js');
if (isDirectRun) {
  seed()
    .then(() => process.exit(0))
    .catch((err) => { console.error("Seeding failed:", err); process.exit(1); });
}
